### ISSUE TITLE
Server Navigation

### ISSUE THREAD

**Issue by JavaCafe01** [cloudrex/discord-term#33]
I know this is stupid but... I can't seem to switch between servers:

Say I'm on Server/Guild A and I want to switch to the Vision Family server/guild:

`/g Vision Family`

Am I doing something wrong? Thanks!

**Comment by cloudrex** [comment]
Hi there! You need to use the server Id. ex. `/g 1234567891234567`. Turn on developer mode on Discord to right-click and copy the server Ids or cope them on the terminal


You can also then use Tags to make this process easier, take a look at README.md.

**Comment by JavaCafe01** [comment]
Thanks! And if you want to link how to get developer mode on the readme, the link is [here](https://discordia.me/developer-mode).
