### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by shrx** [cloudrex/discord-term#38]
Got this error on a fresh install of `dterm`:

```
$ dterm
/usr/local/lib/node_modules/discord-term/dist/app.js:9
async function init() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by cloudrex** [comment]
Hi, thanks for reporting this issue.

What OS and Node.js version are you using?

**Comment by cloudrex** [comment]
This is a common error re-occurring with others as well, usually this should work perfectly with Node >v10, but for some reason the `async` keyword is messing it up (unsupported). I'm going to address this in a future release by using promises instead of top-level async functions.

**Comment by cloudrex** [comment]
@shrx Good news! I've removed the need for this on the latest commits on the dev. branch. Once v1.3.0 is released, this issue should be resolved.
