### ISSUE TITLE
Record dms

### ISSUE THREAD

**Issue by TheBigerGamer** [cloudrex/discord-term#55]
This terminal can record the DMs? Like:
/tag user 123456789
/dm watch user
and we can see all DMs from that user.

**Comment by cloudrex** [comment]
@TheBigerGamer I believe Receiving DMs is already possible.

**Comment by TheBigerGamer** [comment]
Well, I'm getting some trouble with that. I tried to use /track <id>, and
/tag user <id>
/track user
But it says "That user is not cashed."

**Comment by cloudrex** [comment]
@TheBigerGamer Are you sure you're using the `tag` command correctly? It should be "/tag someone 12345123451234" then "/track $someone" (1234... being their Discord ID).

**Comment by cloudrex** [comment]
This program uses the library "curses" to create and render the terminal GUI that you see. You may tweak it around see what you can accomplish if you choose to fork the repository. There may also be better alternatives out there.
