### ISSUE TITLE
How do we use this program?

### ISSUE THREAD

**Issue by bparker06** [cloudrex/discord-term#65]
I couldn't find any documentation and it's not immediately obvious to me how to use the program. When I run dterm I get a screen with `<System> Applied theme 'default' (0 bytes)` and a prompt, but now I have no clue what to do. Typing in anything at all and pressing enter just makes the cursor go away and the program appears to hang, or at least does not show anything different.

**Comment by cloudrex** [comment]
Great point! I'll be sure to place details on usage on the README file on the future.

Try typing /help to display all available commands.
Use /login <token> to connect the Discord client and begin chatting.

[Here's an useful guide on finding your user token](https://discordhelp.net/discord-token), [or if you're planning on using a bot click here](https://discordapp.com/developers/applications/me).

**Comment by bparker06** [comment]
Unfortunately the same thing happens with `/help` or `/login`, the cursor just disappears and then nothing happens. I have to kill the node process.

**Comment by cloudrex** [comment]
What version of the program are you using? Did you install it globally? ex. `npm install -g discord-term`

**Comment by bparker06** [comment]
It is version 0.1.1 and yes it is installed globally.

**Comment by cloudrex** [comment]
What operating system are you using? I've just installed & tested it on Windows 10 and it works as expected.

If you're using Windows, ensure you have the global NPM package executables on your PATH variable (although since you're seeing `<System> Applied ...` message you already have this).

![image](https://user-images.githubusercontent.com/41349879/65293564-a3d07300-db29-11e9-8df6-f27bb91d2a3e.png)

**Comment by bparker06** [comment]
I'm using Ubuntu 18.04, and I'm connecting over SSH so there is no clipboard.

**Comment by cloudrex** [comment]
SSH is the problem. I'd strongly discourage using SSH since having complex UIs through SSH is usually a problem, but more in this case since it's neither designed for SSH nor tested on it.

**Comment by bparker06** [comment]
Yikes. That is literally the only reason I'd want to use such a program. And everything else I've found seems to be either broken or abandoned. Oh well.

**Comment by cloudrex** [comment]
It's more of an SSH problem, since SSH is usually limited in terms of complex UIs, etc.
